main/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("order/", order, name="order"),
    path("order/main/<int:id>/", order_main, name="main"),
    path("order/update/<int:id>/", update, name="update"),
    path("", index, name="home"),
]

project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",  include('main.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models


class Catigori_woork(models.Model):
    name = models.CharField(verbose_name=("Названия катигория"), max_length=50)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "Катигория"
        verbose_name_plural = "Катигории"


class Sotrudnic(models.Model):
    img = models.ImageField(
        upload_to="Woor", verbose_name="Изображения сотрудника",
    )
    name = models.CharField(verbose_name="Имя", max_length=60)
    email = models.EmailField(verbose_name=("email"), max_length=254)
    jod = models.ForeignKey(
        to=Catigori_woork, on_delete=models.CASCADE, related_name="Sotrudnnic"
    )

    def __str__(self) -> str:
        return f'{self.name} -> {self.jod}'
        # return f'{self.name}->{self.img}'

    class Meta:
        verbose_name = "Сатрудник"
        verbose_name_plural = "Сатрудники"


class Task(models.Model):
    img = models.ImageField(upload_to='Woork', verbose_name="Изображения",)
    name = models.CharField(verbose_name="Названия задания",max_length=25)
    description = models.TextField(verbose_name="Описание")
    who_develops = models.ManyToManyField(to=Sotrudnic,related_name='devs')
    date_end = models.DateTimeField(
        verbose_name=("Срок до"), auto_now=False
    )

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "Зада́ние"
        verbose_name_plural = "Зада́ния"

main/forms.py
from typing import Any, Mapping
from django import forms
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList 
from .models import Sotrudnic,Task

class SotrudnicForm(forms.ModelForm):
    def __init__(self,*args, **kwargs) -> None:
        super().__init__(*args,**kwargs)
        self.fields['jod'].empty_label = 'Не выбранно'

    class Meta:
        model = Sotrudnic
        fields = ('img','name','email','jod',)
        labels = {
            "jod": ("должность"),
        }
        widgets = {
            'name':forms.TextInput(attrs={'calass':'input-name'}),
            'email':forms.TextInput(attrs={'calass':'input-name'}),
        }


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('img','name','description','who_develops','date_end')


class UpdateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('img','name','description','who_develops','date_end')

        widgets = {
            'img': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control',}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'cols': '5'}),
            'who_develops': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'date_end': forms.DateInput(attrs={'class': 'form-control'}),
        }

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from main.models import Sotrudnic, Catigori_woork, Task
from django.core.paginator import Paginator
from .forms import SotrudnicForm, TaskForm, UpdateForm


def index(req):
    form = SotrudnicForm()
    if req.method == "POST":
        create(req)
        # form = SotrudnicForm(req.POST, req.FILES)
        # if form.is_valid():
        #     form.save()
        #     return redirect("home")
    work = Sotrudnic.objects.all()

    deliteOk = req.GET.get("deliteOk", None)

    if deliteOk:
        id_del = Sotrudnic.objects.get(pk=deliteOk)
        id_del.delete()
        return redirect("home")

    sorch_work = req.GET.get("sorch", 0)

    if sorch_work:
        work = Sotrudnic.objects.filter(name__icontains=sorch_work)

    catigori_work = req.GET.get("catigori", 0)

    if catigori_work:
        work = Sotrudnic.objects.filter(jod_id__name__icontains=catigori_work)

    page = int(req.GET.get("page", 1))
    page_size = int(req.GET.get("page_size", 8))

    pagin = Paginator(work, page_size)
    work = pagin.get_page(page)

    if not catigori_work:
        catigori_work = 0

    return render(
        req,
        "components/workers.html",
        {
            "h1": "Сатрудники",
            "activ": False,
            "img_user": work,
            "catigori": Catigori_woork.objects.all(),
            "catigori_peng": catigori_work,
            "form": form,
        },
    )

def create(req):
    form = SotrudnicForm(req.POST, req.FILES)
    if form.is_valid():
        form.save()
        return redirect("home")
    pass


def order(req):
    sorch_work = req.GET.get("sorch", 0)
    work = Task.objects.all()
    work_sotrudnik = Sotrudnic.objects.all()
    if sorch_work:
        work = Task.objects.filter(name__icontains=sorch_work)

    page = int(req.GET.get("page", 1))
    page_size = int(req.GET.get("page_size", 8))

    pagin = Paginator(work, page_size)
    work = pagin.get_page(page)

    deliteOK = req.GET.get("deliteOk", None)

    if deliteOK:
        del_order = Task.objects.get(pk=deliteOK)
        del_order.delete()
        redirect("order")
    form = TaskForm()
    if req.method == "POST":
        form = TaskForm(req.POST, req.FILES)
        if form.is_valid():
            form.save()
            return redirect("order")

    return render(
        req,
        "components/order.html",
        {
            "h1": "Задачи",
            "activ": True,
            "img_user": work,
            "work": work_sotrudnik,
            "form": form,
        },
    )


def order_main(req, id):
    work = Task.objects.get(id=id)
    dev = get_object_or_404(Task, id=id)

    return render(
        req,
        "components/order_main.html",
        {
            "h1": "Задача",
            "activ": True,
            "order": work,
            "dev": dev,
        },
    )


def update(req, id):
    work = get_object_or_404(Task, id=id)

    form = UpdateForm(instance=work)
    if req.method == 'POST':
        form = UpdateForm(req.POST,req.FILES,instance=work)
        if form.is_valid():
            form.save()
            return redirect('order')

    return render(
        req,
        "components/udate.html",
        {
            "order_q": work,
            "forms": form,
            "catigori": Sotrudnic.objects.all()
        },
    )

main/templates/components/carts.html
{% load carts %}

{% get_all_worker as workers %}
{% load static %}

<div class="cart">
  {% for user in img_user %}
    <div class="blok">
      <div id="top">
        <img src="{{ user.img.url }}" alt="user" />
      </div>
      <div id="bottom">
        <h4>{{ user.name }}</h4>
        <span>{{ user.email }}</span>
        <span>{{ user.date_end }}</span>
        <h3>{{ user.jod }}</h3>
      </div>

      <div class="delite-a">
        {% comment %} <a href="?delite={{ user.id }}">
          <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="35" height="35" viewBox="0 0 32 32">
            <path d="M 15 4 C 14.476563 4 13.941406 4.183594 13.5625 4.5625 C 13.183594 4.941406 13 5.476563 13 6 L 13 7 L 7 7 L 7 9 L 8 9 L 8 25 C 8 26.644531 9.355469 28 11 28 L 23 28 C 24.644531 28 26 26.644531 26 25 L 26 9 L 27 9 L 27 7 L 21 7 L 21 6 C 21 5.476563 20.816406 4.941406 20.4375 4.5625 C 20.058594 4.183594 19.523438 4 19 4 Z M 15 6 L 19 6 L 19 7 L 15 7 Z M 10 9 L 24 9 L 24 25 C 24 25.554688 23.554688 26 23 26 L 11 26 C 10.445313 26 10 25.554688 10 25 Z M 12 12 L 12 23 L 14 23 L 14 12 Z M 16 12 L 16 23 L 18 23 L 18 12 Z M 20 12 L 20 23 L 22 23 L 22 12 Z"></path>
          </svg>
        </a> {% endcomment %}
        <button value="{{ user.id }} {{user.name}}">
            <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="35" height="35" viewBox="0 0 32 32">
              <path d="M 15 4 C 14.476563 4 13.941406 4.183594 13.5625 4.5625 C 13.183594 4.941406 13 5.476563 13 6 L 13 7 L 7 7 L 7 9 L 8 9 L 8 25 C 8 26.644531 9.355469 28 11 28 L 23 28 C 24.644531 28 26 26.644531 26 25 L 26 9 L 27 9 L 27 7 L 21 7 L 21 6 C 21 5.476563 20.816406 4.941406 20.4375 4.5625 C 20.058594 4.183594 19.523438 4 19 4 Z M 15 6 L 19 6 L 19 7 L 15 7 Z M 10 9 L 24 9 L 24 25 C 24 25.554688 23.554688 26 23 26 L 11 26 C 10.445313 26 10 25.554688 10 25 Z M 12 12 L 12 23 L 14 23 L 14 12 Z M 16 12 L 16 23 L 18 23 L 18 12 Z M 20 12 L 20 23 L 22 23 L 22 12 Z"></path>
            </svg>
        </button>

      </div>
    </div>
  {% endfor %}
</div>

main/templates/components/main_carts.html
{% load carts %}

{% get_all_worker as workers %}
{% load static %}


<div class="cart">

    {% for user in img_user %}

        <div class="blok">
            <div id="top">
                <img src="{{user.img.url}}" alt="user">
            </div>
            <div id="bottom">
                <h4><a href="main/{{user.id}}">{{user.name}}</a></h4>
                <span class='end_date'>{{user.date_end}}</span>
            </div>
            <div class="delite-a">
                <button value="{{ user.id }} {{user.name}}">
                    <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="35" height="35" viewBox="0 0 32 32">
                      <path d="M 15 4 C 14.476563 4 13.941406 4.183594 13.5625 4.5625 C 13.183594 4.941406 13 5.476563 13 6 L 13 7 L 7 7 L 7 9 L 8 9 L 8 25 C 8 26.644531 9.355469 28 11 28 L 23 28 C 24.644531 28 26 26.644531 26 25 L 26 9 L 27 9 L 27 7 L 21 7 L 21 6 C 21 5.476563 20.816406 4.941406 20.4375 4.5625 C 20.058594 4.183594 19.523438 4 19 4 Z M 15 6 L 19 6 L 19 7 L 15 7 Z M 10 9 L 24 9 L 24 25 C 24 25.554688 23.554688 26 23 26 L 11 26 C 10.445313 26 10 25.554688 10 25 Z M 12 12 L 12 23 L 14 23 L 14 12 Z M 16 12 L 16 23 L 18 23 L 18 12 Z M 20 12 L 20 23 L 22 23 L 22 12 Z"></path>
                    </svg>
                </button>
                <a class='update' href="{% url "update" id=user.id %}">
                    <img src="{% static "img/edit.png" %}" alt="">
                </a>
              </div>
            
        </div>

    {% endfor %}

</div>

main/templates/components/order.html
{% extends "index.html" %}
{% load static %}

{% block add %}
    <button class='foggel-form'><img src="{% static 'img/+.svg' %}" alt="+"> New Project</button>
{% endblock add %} 

{% block form %}
<form action="{% url "order" %}" method="post" enctype="multipart/form-data">
    <h2>Add Order</h2>
    {% csrf_token %}
    <button type='button' class="exit"> X </button>
    {% comment %} {{form.as_p}} {% endcomment %}

    {% comment %} img {% endcomment %}
    <label for="id_img">
        <p>Изображения:</p>
        <input type="file" name="img" accept="image/*" required="" id="id_img">
    </label>

    {% comment %} order name {% endcomment %}
    <label for="id_name">
        <p>Названия задания:</p>
        <input type="text" name="name" maxlength="25" required="" id="id_name">
    </label>

    {% comment %} dicript {% endcomment %}
    <label for="id_description">
        <p>Описание:</p>
        <textarea name="description" cols="40" rows="10" required="" id="id_description" style="width: 269px; height: 53px;"></textarea>
    </label>

    {% comment %} meny-to-meny {% endcomment %}
    <label for="id_who_develops">
        <p>Кто будет разрабатывать:</p>
        
        <select name="who_develops" required="" id="id_who_develops" multiple="">
            {% for user in work %}
                <option value="{{user.id}}">{{user}}</option>
            {% endfor %}
        </select>
    </label>

    {% comment %} date-end {% endcomment %}
    <label for="id_date_end">
        <p>Срок до:</p>
        <input type="date" name="date_end" required="" id="id_date_end">
    </label>

    <button type="submit">Добавить</button>
</form>
{% endblock form %} 

{% block delite %}
<p>Вы точно хотите удолить "<b>{{delite.name}}</b>"</p>

<div class="chois">
    <a href="">Отмена</a>
    <a href="?deliteOk={{ delite.id }}">Ок</a>
</div>               
{% endblock delite %} 

{% block sorch %}
    <form action="{% url "order" %}" method="get">
        <input type="text" name='sorch'>
        <button type="submit"><img src="{% static 'img/sorch.svg' %}" alt="sorch"></button>
    </form>
{% endblock sorch %}

{% block main %}
{% include "components/main_carts.html" %}
{% include "components/page.html" %}
{% endblock main %}

main/templates/components/order_main.html
{% extends "index.html" %}
{% load static %}


{% block main %}
<div class="order_blok">
    <div class="left">
        <img src="{% static "img/cover.svg" %}" alt="" class="fon">
        <div class="top">
            <img src="{{order.img.url}}" alt="asd">
            <h2>{{order.name}}</h2>
            
            <div class="discription">
                <h3>Description:</h3>
                <p>{{order.description}}</p>
            </div>
            <div class="time">
                <li>Date-End</li>
                <span>Закончить до: {{order.date_end}}</span>
            </div>
            
        </div>
    </div>
    <div class="reght">
        <div class="blok_content_dev">
            <h3>Developers</h3>
        </div>
        {% for i in dev.who_develops.all %}
            <div class="blok_dev">
                <div class="left_blok">
                    <img src="{{i.img.url}}" alt="">
                </div>
                <div class="reght_blok">
                    <h5> {{i.name}}</h5>
                    <p>jod: {{i.jod}}</p>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock main %}

main/templates/components/page.html
{% load static %}

{% if img_user.has_previous or img_user.has_next %}
    <nav id='nav'>
        <ul class="pagination">
            {% if img_user.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ img_user.previous_page_number }}{% if catigori_peng %}&catigori={% if catigori_peng  %}{{catigori_peng}}{% endif %} {% endif %}">
                        <svg width="12.560059" height="20.910522" viewBox="0 0 12.5601 20.9105" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                            <desc>
                                    Created with Pixso.
                            </desc>
                            <defs/>
                            <path id="Vector" d="M10.8 20.63L0.33 11.19C-0.12 10.8 -0.12 10.1 0.33 9.71L10.8 0.27C11.47 -0.33 12.56 0.11 12.56 1.01L12.56 19.89C12.56 20.79 11.47 21.23 10.8 20.63Z" fill="#A098AE" fill-opacity="1.000000" fill-rule="nonzero"/>
                        </svg>     
                    </a>
                </li>
            {% endif %}

            {% for i in img_user.paginator.page_range %}
                {% if img_user.number == i %}
                    <li class="page-item-num active">
                        <span class="page-link">{{ i }}</span>
                    </li>
                {% else %}
                    <li class="page-item-num">
                        <a class="page-link" href="?page={{ i }}{% if catigori_peng %}&catigori={% if catigori_peng  %}{{catigori_peng}}{% endif %} {% endif %}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if img_user.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ img_user.next_page_number }}{% if catigori_peng %}&catigori={% if catigori_peng  %}{{catigori_peng}}{% endif %} {% endif %} ">
                        <svg width="12.560059" height="20.910522" viewBox="0 0 12.5601 20.9105" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                            <desc>
                                    Created with Pixso.
                            </desc>
                            <defs/>
                            <path id="Vector" d="M1.75 0.27L12.22 9.71C12.67 10.1 12.67 10.8 12.22 11.19L1.75 20.63C1.08 21.23 0 20.79 0 19.89L0 1.01C0 0.11 1.08 -0.33 1.75 0.27Z" fill="#A098AE" fill-opacity="1.000000" fill-rule="nonzero"/>
                        </svg>                     
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

main/templates/components/udate.html
{% extends "index.html" %}

{% block main %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<h3 class="mb-4">Create order "{{order_q.name}}"</h3>

    <form action="{% url 'update' id=order_q.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

       {{forms.as_p}}
        
        <button type="submit">Update</button>

    </form>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
{% endblock main %}

main/templates/components/workers.html
{% extends "index.html" %}
{% load static %}


{% block catigori %}
    <a href="/?catigori=">All</a>
    {% for i in catigori %}
        <a href="/?catigori={{i.name}}">{{i.name}} </a>
    {% endfor %}
{% endblock catigori %}


{% block form %}
<form action="{% url "home" %}" method="post" enctype="multipart/form-data">
    <h2>Add Worker</h2>
    {% csrf_token %}
    <button type='button' class="exit"> X </button>
    {% comment %} img {% endcomment %}
    <label for="id_img">
        <p>Изображения сатрудника:</p>
        <input type="file" name="img" accept="image/*" required="" id="id_img">
        {{form.img.error}}
    </label>
    {% comment %} name {% endcomment %}
    <label for="id_name">
        <p>Имя:</p>
        <input type="text" name="name" calass="input-name" maxlength="60" required="" id="id_name">
    </label>

    {% comment %} email {% endcomment %}
    <label for="id_email">
        <p>Email:</p>
        <input type="email" name="email" calass="input-name" maxlength="254" required="" id="id_email">
        {{form.email.error}}
    </label>

    {% comment %} jod {% endcomment %}
    <label for="id_jod">
        <p>Работа:</p>
        <select name="jod" required="" id="id_jod">
            <option value="" selected="">Не выбранно</option>
            {% for item in catigori %}
            <option value="{{item.id}}">{{item.name}}</option>
            {% endfor %}
        </select>
    </label>
        
    

    <button type="submit">Добавить</button>
</form>
{% endblock form %} 


{% block catigori_mobail %}
    <select class='select-model' name="" id="">
        <option value="/?catigori=">
            выберите катигорию
        </option>
        <option value="/?catigori=">
               <a href="/?catigori=">All</a>
        </option>
        {% for i in catigori %}
        <option value="/?catigori={{i.name}}">
            <a href="/?catigori={{i.name}}">{{i.name}} </a>
        </option>
            {% endfor %}
                
    </select>
{% endblock catigori_mobail %}


{% block add %}
    <button class='foggel-form'><img src="{% static 'img/+.svg' %}" alt="+"> New Employee</button>
{% endblock add %}


{% block sorch %}
    <form action="{% url "home" %}" method="get">
        <input type="text" name='sorch'>
        <button type="submit"><img src="{% static 'img/sorch.svg' %}" alt="sorch"></button>
    </form>
{% endblock sorch %}

{% block main %}
    {% include "components/carts.html" %}
    {% include "components/page.html" %}
{% endblock main %}


{% block delite %}

<p>Вы точно хотите удолить "<b>{{delite.name}}</b>"</p>

<div class="chois">
    <a href="">Отмена</a>
    <a href="?deliteOk={{ delite.id }}">Ок</a>
</div>


{% endblock delite %}